# Generated by Django 5.1.4 on 2025-01-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_alter_play_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="rows",
            new_name="row",
        ),
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(related_name="plays", to="theatre.actor"),
        ),
    ]
