# Generated by Django 5.1.4 on 2025-01-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_rename_rows_ticket_row_alter_play_actors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theatrehall",
            old_name="rows",
            new_name="row",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
    ]
